# Generated by Django 6.0.2 on 2026-02-10 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='DatasetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField()),
                ('avg_flowrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_flowrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_flowrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='equipment_api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(max_length=50)),
                ('flowrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='equipment_api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTypeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_flowrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_stats', to='equipment_api.dataset')),
            ],
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['user', 'upload_date'], name='equipment_a_user_id_dbf834_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['file_hash'], name='equipment_a_file_ha_a7a926_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['is_active'], name='equipment_a_is_acti_f1b22f_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdata',
            index=models.Index(fields=['dataset', 'equipment_type'], name='equipment_a_dataset_8a438a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmenttypestats',
            unique_together={('dataset', 'equipment_type')},
        ),
    ]
